version: '3.8'

services:
  line-file-uploader:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - GOOGLE_CREDENTIALS_JSON=${GOOGLE_CREDENTIALS_JSON}
      - UPLOAD_FOLDER_ID=${UPLOAD_FOLDER_ID}
      - PORT=8000
    volumes:
      - ./temp_files:/app/temp_files
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 